language: scala

scala:
  - 2.10.2
  - 2.10.3

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  - TERM=dumb
  - PROJECT=Core
  - PROJECT=Compatibility:BinniesMods:ExtraTrees:Materials:Wood
  - PROJECT=Compatibility:BiomesOPlenty:Materials:Wood
  - PROJECT=Compatibility:ExtraBiomesXL:Materials:Wood
  - PROJECT=Compatibility:Forestry:Materials:Wood
  - PROJECT=Compatibility:Natura:Materials:Wood
  - PROJECT=Compatibility:Thaumcraft:Materials:Wood
  - PROJECT=Compatibility:Vanilla:Materials:Wood

install:
  - gradle :$PROJECT:setupCIWorkspace

script: gradle :$PROJECT:assemble

after_success:
  - gradle :$PROJECT:cobertura :$PROJECT:coveralls
