language: scala

scala:
  - 2.10.2
  - 2.10.3

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  - TERM=dumb

install:
  - ./gradlew setupCIWorkspace
  
script: ./gradlew buildNeeded

after_success:
- ./gradlew cobertura
- ./gradlew coveralls
